### ISSUE TITLE
global update of npm  as root may broke actual npm 

### ISSUE THREAD

**Issue by jakubmichalko** [Akram-Adel/watcher#1]
https://github.com/Akram-Adel/watcher/blob/5c41288baed16cb71124c0cfb34e0ff074745dfd/.husky/pre-commit#L10

**Comment by Akram-Adel** [comment]
Since this package is not hosted yet on npm, we have to rely on the root directory for installing & updating the package, hence the use of `npm update -g .`. I don't see a potential problem with this approach.

We are working on modifications to the script functionalities that allow changing the configurations directly from the terminal without requiring manual modifications to the `configs.json` file, thus eliminating the use of global updating completely. Stay tuned 😄
